### ISSUE TITLE
ERROR[Main]: Ignoring escape sequence 'c@#ffffff' in translation

### ISSUE THREAD

**Issue by bialad** [minetest-mods/i3#10]
I get this every time I open the inventory, I don't know how to check my locale in minetest but my OS locale is en_us.

I run mineclone2 on minetest 5.4.0.

**Comment by kilbith** [comment]
This game is not officially supported. Please tell me if this error is showing on any other game.

**Comment by kilbith** [comment]
Fixed: https://github.com/minetest-mods/i3/commit/6dfc8fe5981df22899e986df63a2d15459bde5c6
