### ISSUE TITLE
i3/init.lua:2304: attempt to call field 'get_award_states' (a nil value)

### ISSUE THREAD

**Issue by bialad** [minetest-mods/i3#11]
I get this error if I start i3 without the (optional) awards mod enabled.

**Comment by kilbith** [comment]
It's caused by a fork of `awards` in MineClone2. @Wuzzy2 should probably update it or rename it, I don't know.
The only supported `awards` mod is the upstream one by rubenwardy.

**Comment by Wuzzy2** [comment]
Please do not “@” me anymore when it's about MCL2 feature requests (unless you want to know something specific about MCL2 history), I am no longer working on MCL2. MCL2 has new maintainers now: kay27 and EliasFleckenstein (see the MCL2 forum thread).
