### ISSUE TITLE
Forces loop of main menu

### ISSUE THREAD

**Issue by BugReportering** [minetest-mods/i3#12]
With the mod installed there is an issue where it force loops the main menu. Pressing escape returns to the main menu instead of closing it.  Pressing continue button also does the same.

### **Minetest server info:** 
```
Minetest 5.4.0 (Linux)
Using Irrlicht 1.8.4
Using Lua 5.1.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
```

**Comment by kilbith** [comment]
Pressing escape from where?

Please give me **clear** steps to reproduce.

**Comment by BugReportering** [comment]
Pressing escape or continue from the menu in the server: 
![Minetest_menu](https://user-images.githubusercontent.com/66106762/110996589-22d2f000-834a-11eb-866f-5b4e9a86b23e.png)

Steps: 
1) install mod,
2) load mod
3) enter server
Then the menu pops up without pressing escape, and stays on screen even with escape or continue button.

**Comment by kilbith** [comment]
There's absolutely no relationship between a mod and the pause menu. Both are perfectly separate and they cannot interact.

**Comment by BugReportering** [comment]
So why does it only happen with this mod enabled then?

**Comment by BugReportering** [comment]
it also shows:  
ERROR[Main]: Ignoring escape sequence 'c@#ffffff' in translation

**Comment by kilbith** [comment]
Which game? Minetest Game? MineClone2?

**Comment by BugReportering** [comment]
Minetest game loaded from dedicated server.

**Comment by kilbith** [comment]
After which specific actions?

**Comment by BugReportering** [comment]
Opening inventory.

**Comment by kilbith** [comment]
Do you have the mods `awards` and `mtg_plus` installed?

**Comment by BugReportering** [comment]
Yes, both.

**Comment by kilbith** [comment]
Fixed: https://github.com/minetest-mods/i3/commit/6dfc8fe5981df22899e986df63a2d15459bde5c6

**Comment by BugReportering** [comment]
Thanks. I'm heading out now, I'll check it later when I get home.

**Comment by BugReportering** [comment]
issue seems to be resolved. Thank you.
