### ISSUE TITLE
Features and mods support request

### ISSUE THREAD

**Issue by 3raven** [minetest-mods/i3#16]
Hi,
Just a list of mods support and features I would like to see in your mod

mods 
-worldedit interface
-upgrade_packs and more_upgrade
-advmarkers

features
-sethome and home button
-enable recipe in creative mode
-bags ; dont reduce the size of slots (makes it hard to see and manipulate items)
-bags ; bigger capacity

**Comment by kilbith** [comment]
- WorldEdit GUI is planned, however there's no API for it.
- upgrade_packs and more_upgrade are not notable enough, so it's a no.
- Same for advmarkers.
- For the rest, it's a nope too.

But I do plan to add waypoints with teleportation and maybe a `areas` GUI.

**Comment by kilbith** [comment]
Markers are now implemented.

**Comment by Ygarr** [comment]
How about "just" shortcut for WorldEdit GUI like in Inventory plus? Is it possible

**Comment by kilbith** [comment]
I don't like shortcut, it has to be a proper integration.
