### ISSUE TITLE
crafts with minetest.itemstring_with_palette output not coloring correctly in craft guide

### ISSUE THREAD

**Issue by wsor4035** [minetest-mods/i3#18]
as found here, https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L762-L769 registering a similar craft will not show the proper color in the crafting guide, but will show the proper color in crafting grid when you go to craft the item

**Comment by kilbith** [comment]
Do you have an example recipe to show me? I never used color palette.

**Comment by wsor4035** [comment]
the project im currently working is not released yet, however i would assume the craft linked above, https://gist.github.com/juhdanad/433a0aa7094ae0dceaf00924d6fd1e3b and https://github.com/minetest/minetest/pull/5640#issuecomment-302868234 for textures combined could make a simple demo mod, if you wish i could put it together

**Comment by kilbith** [comment]
Give me this mod.

**Comment by wsor4035** [comment]
https://github.com/wsor4035/i3_color_demo there, put together 
![image](https://user-images.githubusercontent.com/24964441/113744335-a1fdde80-96d2-11eb-996f-8a29e090662f.png)

**Comment by kilbith** [comment]
Thanks for the help.

Unfortunately, this is impossible to support without weird hacks, and even then, the support would be very partial.

There is no way to get the palette dimensions from a mod, there is no way to get a color from a pixel, and a proper displaying would need the ability to create a new item or to modify an item definition at runtime.

**Comment by wsor4035** [comment]
ah, thanks for looking at it, should I file a issue for it, or do you already have that covered?

**Comment by kilbith** [comment]
Support added: https://github.com/minetest-mods/i3/commit/7a48b93719c92001690ea4f77d6f5a6f576dff07

**Comment by wsor4035** [comment]
Thank you
