### ISSUE TITLE
No trash in survival / option

### ISSUE THREAD

**Issue by daretmavi** [minetest-mods/i3#20]
Hi JP.

I know you don't like adding too much settings or changing the gui style, but maybe you could reconsider this.

Many people don't like inventory trash in the survival, but it is very useful in creative.

I use this small patch to remove the buttons in survival:
<details>
<summary>Patch</summary>

```
diff --git a/init.lua b/init.lua
index 3bb0605..9f308b5 100644
--- a/init.lua
+++ b/init.lua
@@ -1893,9 +1893,13 @@ local function get_ctn_content(fs, data, player, yoffset, ctn_len, award_list, a
 
 	fs(fmt("list[current_player;craft;%f,%f;3,3;]", 0, yoffset + 1.45))
 	fs("image", 3.47, yoffset + 2.69, 0.85, 0.85, PNG.arrow)
-	fs(fmt("list[current_player;craftpreview;%f,%f;1,1;]", 4.45, yoffset + 2.6),
-	   fmt("list[detached:i3_trash;main;%f,%f;1,1;]", 4.45, yoffset + 3.75))
-	fs("image", 4.45, yoffset + 3.75, 1, 1, PNG.trash)
+	fs(fmt("list[current_player;craftpreview;%f,%f;1,1;]", 4.45, yoffset + 2.6))--,
+	--   fmt("list[detached:i3_trash;main;%f,%f;1,1;]", 4.45, yoffset + 3.75))
+	--fs("image", 4.45, yoffset + 3.75, 1, 1, PNG.trash)
+	if core.is_creative_enabled(name) then
+		fs(fmt("list[detached:i3_trash;main;%f,%f;1,1;]", 4.45, yoffset + 3.75))
+		fs("image", 4.45, yoffset + 3.75, 1, 1, PNG.trash)
+	end
 
 	local yextra = 5.5
 
@@ -2388,11 +2392,12 @@ local function get_inventory_fs(player, data, fs)
 	fs("scroll_container_end[]")
 
 	local btn = {
-		{"trash", ES"Trash all items"},
+		--{"trash", ES"Trash all items"},
 		{"sort_az", ES"Sort items (A-Z)"},
 		{"sort_za", ES"Sort items (Z-A)"},
 		{"compress", ES"Compress items"},
 	}
+	if core.is_creative_enabled(name) then table.insert(btn, 1, {"trash", ES"Trash all items"}) end
 
 	for i, v in ipairs(btn) do
 		local btn_name, tooltip = unpack(v)
```
</details>

It would be even better with some settingtype, so everyone can adapt this great gui to his game play style.

**Comment by kilbith** [comment]
No, sorry, I'm not interested in hiding the trash functions in survival mode. I haven't heard anyone yet complaining about that.

**Comment by daretmavi** [comment]
OK, I read it on the [forum](https://forum.minetest.net/viewtopic.php?t=26332&p=391982#p391982).

It is your mod, so I suppose I have to live with it.
I still believe, that mod like this should have settings for ... everything. It is good for interoperability and makes game devs life easier. Different games = different game-play-styles = different settings. This is a big problem with many mods. It is almost impossible to add more mods and get  working game in Minetest.

Anyway, still the best gui, keep working and I hope you will change mind eventually :+1:
