### ISSUE TITLE
bug: craft guide shows wrong description from meta when output is used in the craft

### ISSUE THREAD

**Issue by wsor4035** [minetest-mods/i3#22]
demo mod latest commit: https://github.com/wsor4035/i3_color_demo

this happens when using a item that is also the output of the recipe, the bottom craftguide custom description overrides the top craftguide description, see attached photos

![image](https://user-images.githubusercontent.com/24964441/114280763-d8a46380-9a08-11eb-9184-8426c73c8638.png)
![image](https://user-images.githubusercontent.com/24964441/114280768-e35ef880-9a08-11eb-9c68-c67230a09057.png)
![image](https://user-images.githubusercontent.com/24964441/114280770-ed80f700-9a08-11eb-914b-ae06a189b80d.png)

**Comment by kilbith** [comment]
Fixed: https://github.com/minetest-mods/i3/commit/d8cfead5adc4ca69e26175fbac41857e747f7384

Thanks for reporting.
