### ISSUE TITLE
hardware colorized nodes in craftguide output boxes arent stylized

### ISSUE THREAD

**Issue by wsor4035** [minetest-mods/i3#23]
see title

im not sure if this is a bug, or a limitation of colorizing nodes?

image for context
![image](https://user-images.githubusercontent.com/24964441/114288880-13c28900-9a41-11eb-973a-0b681947dbc5.png)

**Comment by kilbith** [comment]
Yes that was necessary...

**Comment by wsor4035** [comment]
ah, thanks

**Comment by kilbith** [comment]
By latest commit, colored item stacks are now showing properly.
