### ISSUE TITLE
Bug: restart causes item loss past slot 36 when using bags

### ISSUE THREAD

**Issue by wsor4035** [minetest-mods/i3#26]
see issue title, another thing I have noticed when working on a project that uses i3
steps to reproduce
1. add a bag in the bag slot
2. add any item past slot 36 and a a item before slot 36
3. close and reopen world
4. observe item before slot 36 is still there, and item past slot 36 is gone

**Comment by kilbith** [comment]
Fixed: https://github.com/minetest-mods/i3/commit/51866ee8c8b7a78fd38b664c9c2bee31b69b734a

**Comment by wsor4035** [comment]
thank you
