### ISSUE TITLE
skinsdb - skin set without i3

### ISSUE THREAD

**Issue by daretmavi** [minetest-mods/i3#28]
If you set the skin without i3, then later in i3-skinsdb drop-down list the skin name is not correct.
(e.g. if you switch from sfinv to i3)

You could get the actual skin name by `skins.get_player_skin(player).name`

**Comment by kilbith** [comment]
https://github.com/minetest-mods/i3/commit/7e2256253d44157c0b49fb841ab514b0b3417711
