### ISSUE TITLE
API for backpacks

### ISSUE THREAD

**Issue by grapereader** [minetest-mods/i3#33]
The current backpack support is hard-coded and the recipes depend on minetest-game/farming for string. This seems out-of-place in what should be a generic inventory implementation.

Proposed solution:
1. Define no backpacks by default
2. Create a new API call `i3.register_backpack(itemid, backpack_defn)` which takes an existing registered item and adds the backpack behaviour to it. `backpack_defn` is a table with whatever properties make sense for a backpack (I imagine slot width and height, at a minimum).

If desired, the existing backpacks could be extracted to a companion mod i3-backpacks which uses the new call. This would have the added benefit of serving as an example implementation.

**Comment by wsor4035** [comment]
this seems like a over complicated solution to just overriding the craft for bags

**Comment by wsor4035** [comment]
solution for allowing completely custom backpacks to work while trying to remain as agnostic as possible would be changing https://github.com/minetest-mods/i3/blob/main/init.lua#L2956 to use `minetest.get_item_group` custom backpacks would need to simply add i3_backpack = #1-3 or whatever you want the group name to be
