### ISSUE TITLE
Crash when "Preview the waypoint area"

### ISSUE THREAD

**Issue by GreenDirkfried** [minetest-mods/i3#41]
I used the latest version from the minetest db, which should be 1.5.1, and have a crash in local game, when clicking on "Preview the waypoint area". 
The error message is:

WARNING[Server]: Undeclared global variable "bit" accessed at (load):273
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback on_playerReceiveFields(): (load):273: attempt to index global 'bit' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	(load):273: in function 'get_isometric_view'
ERROR[Main]: 	(load):375: in function 'get_waypoint_fs'
ERROR[Main]: 	(load):518: in function 'get_container'
ERROR[Main]: 	(load):699: in function 'formspec'
ERROR[Main]: 	(load):1498: in function 'make_fs'
ERROR[Main]: 	(load):169: in function 'fields'
ERROR[Main]: 	(load):460: in function <(load):422>
ERROR[Main]: 	../minetest/builtin/game/register.lua:422: in function <../minetest/builtin/game/register.lua:406>

**Comment by kilbith** [comment]
Oh shit, I forgot I was using 5.5 stuff there.

**Comment by kilbith** [comment]
Fixed: https://github.com/minetest-mods/i3/commit/edf0867e6c5adbe0c3d4a52a8e94512a70f0b160
