### ISSUE TITLE
legacy inventory hud bar visual glitch (boxes size / position)

### ISSUE THREAD

**Issue by Sharpik** [minetest-mods/i3#43]
Hi, I'd like to report visual glitch with item boxes at bottom in hud bar.

![obrazek](https://user-images.githubusercontent.com/3375029/147371897-12e0200d-6318-4747-8c07-53d6bc3d0f4d.png)

But rally thanks for Your recent legacy inventory support.

**Comment by Sharpik** [comment]
Possible fix:
https://github.com/Sharpik/i3/commit/c196a8392067348320fcbcf04049773bffc4881d

https://github.com/Sharpik/i3/blob/main/textures/i3_hotbar_8slots.png (Needed for textures packs for possible overlay)

**Comment by kilbith** [comment]
Fixed: https://github.com/minetest-mods/i3/commit/2fadcdefddeb3bed3a98fbaf441ca6e787b4ad70
