### ISSUE TITLE
Opening i3 triggers errors in chat

### ISSUE THREAD

**Issue by appgurueu** [minetest-mods/i3#49]
**Screenshots**
![Bildschirmfoto von 2022-01-09 17-58-29](https://user-images.githubusercontent.com/34514239/148692405-8f96c49c-eba1-4519-955c-ef83d0869932.png)

**Comment by kilbith** [comment]
*sigh*

https://github.com/minetest/minetest/commit/8fab406c28bc5a18137d2653356c10880c827613
