### ISSUE TITLE
Hot bar X position not consistent

### ISSUE THREAD

**Issue by JordanL2** [minetest-mods/i3#50]
This is a very minor complaint, but I've noticed that the X position the hotbar starts can change by 2 pixels on startup. I only noticed because I'm trying to get the hudbars mod to line up with it perfectly.

Sometimes, the left x margin (number of pixels between the left of the screen, and the left-most part of the hotbar) is 1024 pixels, sometimes it's 1026. Weirdly the right x margin is consistent - it's always 1026 pixels. This is with a 2560 wide screen. I've scaled the GUI to 1.5 but that doesn't seem to affect i3 (which should probably be another issue ;) ).

I'm using latest i3 on Minetest 5.4.1.

**Comment by kilbith** [comment]
Screenshot please

**Comment by JordanL2** [comment]
I'm an idiot. I looked at the two screenshots showing the x position in different places, and the difference was in one of them I had the first slot selected. And so the selection box added 2 pixels around the slot.
