### ISSUE TITLE
In recipes the recipe type such as "Alloying" text for label not visible but over-over tooltip is.

### ISSUE THREAD

**Issue by mrbid** [minetest-mods/i3#53]
This seems to be because your inventory uses graphics to represent the crafting type, so if it is a cooking recipe it shows a graphic of a furnace, although in Technic there is no graphic for Alloying so the i3 inventory should just show a plain text label saying "Alloying".

**Comment by kilbith** [comment]
It is strongly encouraged to set an icon for custom recipe types.

**Comment by mrbid** [comment]
> It is strongly encouraged to set an icon for custom recipe types.

I bet it is, because that's easier the fixing the problem as it should be. This is not a solution, this is ignorance.
