### ISSUE TITLE
Shift click for armor and bags (remove the scrolling?)

### ISSUE THREAD

**Issue by GreenDirkfried** [minetest-mods/i3#58]
This is another feature request :-D
Shift clicking on items to get them from your inventory to chests and the crafting table is just really useful and I would like to have this also for the bags and armor in i3.
I suggest to add the crafting table to the list of bags, armor, ... 
Also this would remove the scrolling down to get to the bags and armor slots and in my opinion there is no reason why these should be "on the same page" as the crafting table.

**Comment by kilbith** [comment]
Not possible.

**Comment by GreenDirkfried** [comment]
:-( 
Not possible because this would be too much to change?
