### ISSUE TITLE
Feature Request: api method for player inventory form

### ISSUE THREAD

**Issue by wsor4035** [minetest-mods/i3#60]
TLDR: api method for player inventory form

Example: `i3.inventory_fs(x,y)`

Reasoning: when registering a tab with i3, some mod authors may want to have the inventory in the tab, and this forces them to reimplement the inventory list styling/spacing/etc. additionally they will have to make it configurable for https://github.com/minetest-mods/i3/blob/main/settingtypes.txt#L8.

Additional Use Cases: could be useful for mod creators wanting to support i3 by having a api call available to drop into there form, examples (tool, chest, etc)

**Comment by kilbith** [comment]
Not particulary interested in adding a API method for this.

https://github.com/minetest-mods/i3/blob/758e3e0c4defd256579c2b7cdc720dc4b63f577f/src/gui.lua#L126
