### ISSUE TITLE
bug report: players are able to use tabs if they had them opened before there access to view them was revoked

### ISSUE THREAD

**Issue by wsor4035** [minetest-mods/i3#61]
**Describe the bug**
players are able to use tabs if they had them opened before there access to view them was revoked

**Expected behavior**
tab view would revert to inventory view

**To Reproduce**
make a test tab that uses minetest.is_creative_enabled(name) as access. launch a game in survival, grant yourself creative, open test tab, close formspec, revoke creative, open formspec, see tab is gone, but view is still of the test tab

**Screenshots**

bug:
![image](https://user-images.githubusercontent.com/24964441/158477534-2f7a81e6-da55-4838-9b08-a193fa8a8e37.png)

**Additional context**
- Mod version? Release or git?
git
- Engine version?
5.5.0
- LuaJIT enabled?
yes
- Operating system?
windows, linux
- Did you try to disable other mods except i3?
yes

**Comment by kilbith** [comment]
https://github.com/minetest-mods/i3/commit/758e3e0c4defd256579c2b7cdc720dc4b63f577f
