### ISSUE TITLE
[BUG] Misc. settings don't save

### ISSUE THREAD

**Issue by Beethoven-n** [minetest-mods/i3#64]
**Describe the bug**
On changing the Misc. settings in the inventory and quitting the game, then re-entering, your settings are not saved.

**To Reproduce**
- Open the i3 inventory
- Change a Misc. setting
- Quit the game
- Re-enter the game on the world you played on
Your settings will not be restored when you come back.

**Additional context**
- Mod version? Release or git?
Release
- Engine version?
5.5.0
- LuaJIT enabled?
Yes
- Operating system?
Arch Linux
- Did you try to disable other mods except i3?
Yes

**Comments**
Would it be a good idea to add a config file to read from for this?

**Comment by kilbith** [comment]
I'm aware and it is by design. These "settings" are meant to be saved accross sessions. Users are likely to change their inventory sorting preferences.

**Comment by ainola** [comment]
It really is odd design, though. One tab saving the preferences while the other doesn't seems like buggy behavior. I also find myself not wanting to turn off the auto-sorting as well. If I did I could always untick the box myself. :)

Would you reconsider this bug, @kilbith, or at least make some indication that the settings in that tab are temporary?

**Comment by kilbith** [comment]
Grab the latest release, the behavior has changed.

**Comment by ainola** [comment]
How serendipitous! Thanks for doing that.
