### ISSUE TITLE
[FEATURE] Shorthands for search filters

### ISSUE THREAD

**Issue by Beethoven-n** [minetest-mods/i3#65]
The `+param=string` filtering option is really great, but it's a bit unfamiliar, and relatively undocumented.
A more intuitive option might be to also add specific characters for common filtering parameters. For example, to search through all items from moreblocks, you could do either `@moreblocks` or the current `+mods=moreblocks`. To put it in terms of functionality that already exists, it could also work so you could do either `^wood` or `+groups=wood`.

**Comment by kilbith** [comment]
To search through all items from moreblocks, you simply type `moreblocks`.

Do note that search filters are incremental so you can combine them.

**Comment by Beethoven-n** [comment]
you could do the same with shorthands. 
example:
`door @fancydoors ^luxury,wood`
see how this saves characters while still clearly indicating what terms do what?

**Comment by kilbith** [comment]
No, that’s pretty confusing to me. Imagine if there are 10+ search filters.
