### ISSUE TITLE
[Bug]: not having the creative priv, with progressive off, doesnt show certain nodes

### ISSUE THREAD

**Issue by wsor4035** [minetest-mods/i3#66]
**Describe the bug**
without creative priv, and the progressive mode off, certain items will not show up in inventory that do in creative

**To Reproduce**
start mtg with only enable damage enabled from the gui
grant yourself all privs
open inventory
look at all tab
close inventory
revoke creative priv
open inventory
observe all tab

you can easily do this by comparing the bottom right item before and after, else take screenshots

**Expected Behavior**
all tab should stay exactly the same

**Screenshots**
![image](https://user-images.githubusercontent.com/24964441/161397840-434822de-8fc5-41b6-894a-b90fa7aa0b7f.png)

**Additional context**
- Mod version? Release or git? both
- Engine version? 5.5
- LuaJIT enabled? yes
- Operating system? windows, linux
- Did you try to disable other mods except i3? no mods besides mtg and i3

**Comment by kilbith** [comment]
This is the expected behavior. These items don't show up in survival mode as they have no recipes or usages. Thus it doesn't make sense to show them in the list.
