### ISSUE TITLE
[bug]: registering aliases can cause minetest crash when something is searched in i3

### ISSUE THREAD

**Issue by wsor4035** [minetest-mods/i3#68]
**Describe the bug**
trying to search for anything crashes minetest. see https://github.com/mt-mods/unifieddyes/issues/7

**To Reproduce**
use a game without the dye mod
add
```lua
minetest.register_alias("dye:light_red",  "dye:pink")
minetest.register_alias("dye:medium_orange", "dye:brown")
```
enable mod, try to search something, watch the game crash

**Additional context**
- Mod version? Release and git
- Engine version? 5.5.0
- LuaJIT enabled? yes
- Operating system? windows
- Did you try to disable other mods except i3? no, not needed.

**error stack**
```
AsyncErr: Lua: Runtime error from mod 'i3' in callback on_playerReceiveFields(): (load):104: bad argument #2 to 'translate' (string expected, got nil)
stack traceback:
	[C]: in function 'translate'
	(load):104: in function 'search'
	(load):330: in function 'rcp_fields'
	(load):445: in function <(load):411>
	...st\minetest-5.5.0-win64\bin\..\builtin\game\register.lua:425: in function <...st\minetest-5.5.0-win64\bin\..\builtin\game\register.lua:409>
```

**Comment by kilbith** [comment]
I can't seem to reproduce it. More information needed.

Is `unifieddyes` enabled?

**Comment by wsor4035** [comment]
minimally reproducible example use void game + i3 + unified dyes commit (https://github.com/mt-mods/unifieddyes/tree/ed895734f29c4fb214a82bb3bb2ac123b77fdd2e) (pre me adding a work around), then apply the latest commit and notice it doesnt crash anymore

**Comment by kilbith** [comment]
Indeed that happens when `unifieddyes` is enabled, you should have mentionned that.
