### ISSUE TITLE
Minetest-5.6.0 - mod r.12631: error from mod 'i3' in callback on_mods_loaded()

### ISSUE THREAD

**Issue by Sharpik** [minetest-mods/i3#70]
**Describe the bug**

ModError: Runtime error from mod 'i3' in callback on_mods_loaded(): (load):281: bad argument #1 to 'sub' (string expected, got nil)
stack traceback:
	[C]: in function 'sub'
	(load):281: in function 'is_cube'
	(load):45: in function 'cache_groups'
	(load):71: in function 'get_item_usages'
	(load):98: in function 'get_usages'
	(load):108: in function 'cache_usages'
	(load):309: in function 'init_recipes'
	(load):351: in function 'fill_caches'
	(load):111: in function <(load):110>
	...mes\Minetest\minetest-5\bin\..\builtin\game\register.lua:429: in function <...mes\Minetest\minetest-5\bin\..\builtin\game\register.lua:415>

Check debug.txt for details.

**To Reproduce**
Just run the MT Game with I3 mod enabled 

**Additional context**
- Mod version? Release or git? release = 12631
- Engine version? minetest-5.6.0-35ad00623-win64
- Operating system? W10 64b
- Did you try to disable other mods except i3? Yes

**Comment by kilbith** [comment]
i3 + Minetest Game ? No additional mods ? I doubt it.

**Comment by kilbith** [comment]
Can you try this patch ? https://github.com/minetest-mods/i3/commit/dcc4068e46f6125a503e3bd14d8621d20c143497

**Comment by kilbith** [comment]
Assuming it’s fixed.
