### ISSUE TITLE
 Large number of items not shown

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest-mods/i3#72]
**Describe the bug**
 Large number of items not shown

**To Reproduce**
By comparison, you will find that a large number of items are not displayed

**Screenshots**
### unified_inventory    
- page:267        
- 72x267=19224
[![image|690x473](https://raw.githubusercontent.com/Pantyhose-X/Images/main/i3.PNG)](https://raw.githubusercontent.com/Pantyhose-X/Images/main/i3.PNG)

###  i3  
-  page:150
-  96x150=14400
[![image|690x473](https://raw.githubusercontent.com/Pantyhose-X/Images/main/i32.PNG)](https://raw.githubusercontent.com/Pantyhose-X/Images/main/i32.PNG)

**Additional context**
[Here's a list of the mods I use](https://github.com/Pantyhose-X/AllmodsIuse/releases/tag/bug), I didn't find the i3 error in minetest debug.txt! Test it yourself. Problem with i3 code. 
You can also use your installed mods for testing, and it is not difficult to find this problem

Occurs in all I3 versions

**Comment by kilbith** [comment]
[Some people never learn.](https://content.minetest.net/threads/2873/#reply-7698)

You have been told several times already.
