### ISSUE TITLE
Quick Crafting doesn't give `replacements` back

### ISSUE THREAD

**Issue by AFCMS** [minetest-mods/i3#74]
**Describe the bug**
When using quick crafting on a craft with `replacements` defined, these are not given back.

**To Reproduce**
- Install `basic_materials`
- Give yourself the required materials to craft two small motors
- Use quick crafting
- Notice you don't get back any empty spools

**Screenshots**
None

**Additional context**
- Mod version: Latest Git
- Engine version: 5.6-dev
- LuaJIT enabled: Yes
- Operating system: Ubuntu 20.04

**Comment by kilbith** [comment]
Mod version?

It normally has been fixed few weeks ago: https://github.com/minetest-mods/i3/issues/73

**Comment by AFCMS** [comment]
Oops, sorry.

The latest `git pull` I made failed for some reason so I didn't have the *latest* version xD
