### ISSUE TITLE
Feature Request: Different recipe icon for alloying recipes (instead of normal furnace)

### ISSUE THREAD

**Issue by jolesh** [minetest-mods/i3#76]
This is a copy of the original issue from [here](https://gitlab.com/Kimapr/nonsensical_skyblock/-/issues/3) (nonsensical skyblock (game))

-----------------------------------------------------------------------------------------------------

**Cannot craft bronze ingots from copper and tin ingots**

I tried the custom recipe shown in the crafting guide, and I got no output.
7 copper ingot + 1 tin ingot = 8 bronze ingots
This is recommended but it doesn't give an output.
mods/minetest_game/default/craftitems.lua registers the recipe for 9 bronze ingots as as 1 tin ingot surrounded by 8 copper ingots. I tried that one too, and I got no output either.

Edited 1 month ago by [Nicolae Crefelean](https://gitlab.com/kneekoo)

----------------------------------

[Dima Tillyaev ](https://gitlab.com/Kimapr)[@Kimapr](https://gitlab.com/Kimapr) · [1 month ago](https://gitlab.com/Kimapr/nonsensical_skyblock/-/issues/3#note_1078267691)

what i3 shows are "custom recipes" are not regular crafting recipes. if you put your mouse cursor at the right place (for cooking and digging recipes it usually shows an icon, for technic ones it doesn't), you would see that it's an alloying recipe. technic removes a bunch of default recipes, like sandstone and bronze and replaces it with its own. to make bronze you have to use an alloy furnace.

--------------------------------------

[Nicolae Crefelean ](https://gitlab.com/kneekoo)[@kneekoo](https://gitlab.com/kneekoo) · [1 month ago](https://gitlab.com/Kimapr/nonsensical_skyblock/-/issues/3#note_1078453874)

I noticed it's a custom recipe, but players like myself - unfamiliar with "technic" - have no clue how to move on past that. I don't know which is that "right place" to put the mouse cursor to see that's an alloy furnace recipe.
That's why I thought about showing the alloy furnace instead of the regular one that is displayed in the case of regular smelting/cooking recipes. If that would be possible, along with a tooltip mentioning the item name no extra knowledge or guessing would be required. Can Formspec handle that? Can i3 handle that? It would be great.

**Comment by kilbith** [comment]
In the latest releases, the custom recipe type is written below "Custom recipe". Not only under an icon.
