### ISSUE TITLE
Internal Server Error on Player Die

### ISSUE THREAD

**Issue by welchste** [minetest-mods/i3#79]
**Describe the bug**
Any time any character dies, the server crashes and restarts. Booting all players out of the game.

**To Reproduce**
Any player dies.

**Screenshots**
Minetest log message
```
2022-10-29 21:31:29: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'i3' in callback on_dieplayer(): (load):383: attempt to perform arithmetic on local 'ppos' (a table value)
```

**Additional context**
- Mod version? Release or git? From ContentDB
- Engine version?
- LuaJIT enabled?
- Operating system? Ubuntu
- Did you try to disable other mods except i3? Yes

**Comment by kilbith** [comment]
Can't reproduce. Please **complete** the issue template and tell me about the server + clients version.

@appgurueu 5.6 does support `__add` in Vector metatables, right?

**Comment by appgurueu** [comment]
> @appgurueu 5.6 does support `__add` in Vector metatables, right?

[5.5 even](https://dev.minetest.net/Changelog)

**Comment by kilbith** [comment]
Yes, so <5.6 clients should not even be [able](https://github.com/minetest-mods/i3/blob/main/init.lua#L30) to play the game. Unless you have forked the mod.

**Comment by kilbith** [comment]
Upgrade your server.
