### ISSUE TITLE
Strange inventory slots shift in last versions

### ISSUE THREAD

**Issue by Sharpik** [minetest-mods/i3#8]
Hi, I have strange inventory slots shift in last versions of I3.

![screenshot_20210125_090806](https://user-images.githubusercontent.com/3375029/105681515-7fd92a80-5ef1-11eb-9b95-0bb47136b20f.jpg)
![screenshot_20210125_090810](https://user-images.githubusercontent.com/3375029/105681518-810a5780-5ef1-11eb-80df-522c04e3cce5.jpg)

Can You reproduce it?

Thanks

**Comment by HeyITGuyFixIt** [comment]
Looks like you have extra slots. The usually inventory grid is 8 slots wide, while the one you showed for i3 is 9 wide. Which is why it looks shifted.

**Comment by kilbith** [comment]
`i3` has a larger inventory (36 slots by default) than the usual inventory, chests have to be adapted.

On an unrelated note, @Sharpik can you show me your `minetest.conf` please?

**Comment by Sharpik** [comment]
server_announce = true
server_name = SharpNet.Cz
server_url = http:\\sharpnet.unas.cz
# port = 30000
port = 3000
admin-user =
fixed_map_seed = SharpNet.Cz
# mg_name = v7
# max_block_generate_distance = 8
default_password =
default_privs = interact, shout, fast, lumberjack
# max_simultaneous_block_sends_per_client = 40
# default_game = minetest
motd = Vitejte na SharpNetu / Welcome at SharpNet server :)
server_description = http:\\sharpnet.unas.cz (Password protected)!
max_users = 99
# Time in seconds for item entity (dropped items) to live. Setting it to -1 disables the feature.
# item_entity_ttl = 900
only-peaceful-mobs = true
only_peaceful_mobs = true
enable_damage = true
enable-damage = true
creative_mode = false
creative-mode = false
enable_pvp = true
enable-pvp = true
player_transfer_distance = 0
# static_spawnpoint =
disallow_empty_password = true
# enable_rollback_recording = false
# From how far clients know about objects, stated in mapblocks (16 nodes).
# active_object_send_range_blocks = 4
# active_block_range = 3
max_block_send_distance = 14
max_forceloaded_blocks = 16
# server_map_save_interval = 5.3
movement_speed_fast = 10
# server_unload_unused_data_timeout = 29
# server_side_occlusion_culling = true
# Level of logging to be written to debug.txt - type: enum values: , none, error, warning, action, info, verbose
# debug_log_level = action
# Minimal level of logging to be written to chat. - type: enum values: , none, error, warning, action, info, verbose
# chat_log_level = error
disable_fire = false

#mods settings
ethereal.mushroom = 0
item_drop.pickup_sound_gain = 0.1
item_drop.pickup_radius = 1.2
unified_inventory_bags = false
inventorybags_dialable_bag_of_winds = true
treecapitator.moretrees_support = true
unified_inventory_lite = true
vehicles_nodes = true
craft_table_2x2_craft_grid_to_players = false
technic.enable_frames = true
technic.enable_mining_drill = true
technic.enable_flashlight = true
technic.enable_mining_laser = true

secure.http_mods = mapserver
mapserver.url = http://127.0.0.1:29820
mapserver.key =
mapserver.enable_crafting = true
mapserver.send_interval = 2
maintab_LAST = local
menu_last_game = minetest
selected_world_path = A:\Server\Minetest-server\minetest-5.4.0\bin\..\worlds\SharpNet_Cz
mainmenu_last_selected_world = 1
world_config_selected_mod = 115
ethereal.leafwalk = true
elevator_speed = 15
elevator_accel = 1

**Comment by kilbith** [comment]
Show me your client config file, not the server one

**Comment by Sharpik** [comment]
texture_path = Z:\Games\Minetest\minetest-5\textures\Minetest-SharpNet-Photo-Realism-Texturespack\
enable_damage = true
enable_waving_leaves = true
fsaa = 0
enable_waving_water = true
creative_mode = true
enable_parallax_occlusion = true
menu_last_game = minetest
selected_world_path = Z:\Games\Minetest\minetest-5\bin\..\worlds\MCL2
maintab_LAST = online
node_highlighting = box
enable_waving_plants = true
leaves_style = fancy
mip_map = false
anisotropic_filter = false
bilinear_filter = false
trilinear_filter = false
mainmenu_last_selected_world = 1
keymap_chat = KEY_OEM_3
keymap_cmd_local = KEY_PERIOD
doubletap_jump = true
keymap_inventory = KEY_TAB
autojump = true
keymap_decrease_viewing_range_min = KEY_PLUS
keymap_increase_viewing_range_min = KEY_OEM_2
aux1_descends = false
screen_h = 1080
screen_w = 1920
wieldview_update_time = 2
free_move = false
fast_move = true
wieldview_node_tiles = false
server_announce = false
world_config_selected_mod = 289
address = 
name = 
remote_port = 3000
viewing_range = 260
ethereal.mushroom = 0
treecapitator.moretrees_support = true
unified_inventory_lite = true
nodetimer_interval = 0.1
unlimited_player_transfer_distance = false
vehicles_nodes = true
player_transfer_distance = true
mute_sound = false
mg_name = v7
fixed_map_seed = SharpNet.Cz
enable_fog = true
keymap_cmd = KEY_DIVIDE
inventorybags_dialable_bag_of_winds = true
unified_inventory_bags = false
armor_fire_protect = false
main_menu_technical_settings = false
only_peaceful_mobs = true
noclip = false
pitch_move = false

**Comment by Sharpik** [comment]
![screenshot_20210125_210456](https://user-images.githubusercontent.com/3375029/105761076-ee9aa000-5f52-11eb-9c83-54b8dff21607.png)

**Comment by Sharpik** [comment]
Ok, the inventory bug is relevant to the last changes in Minetest engine it self and this mod recent versions.

In last version of MT (#246082800) minetest-5.4.0-8dae7b47f-win64 (25.1.2021)

**It's all right.**

![screenshot_20210125_214133](https://user-images.githubusercontent.com/3375029/105763653-50103e00-5f56-11eb-8bad-99c42e50cf9e.png)

**Comment by Sharpik** [comment]
Is it possible to make extended inv. size configurable via. config ?
It's nice to have bigger inv. size.. But it's strange to use it with default chests GUI where some of grids missing.
I'm preffering consistence og GUIs instead of extension.

Thanks

**Comment by kilbith** [comment]
> Is it possible to make extended inv. size configurable via. config ?

Yes but you will always have a larger inventory size anyway with backpacks. So it's worthless. Chests GUI have to be reworked.
