### ISSUE TITLE
Page registered using `i3.new_page` doesn't work

### ISSUE THREAD

**Issue by AFCMS** [minetest-mods/i3#80]
**Describe the bug**

Tried the following code: 
```lua
i3.new_tab("minify", {
    description = "Minify",
    image = "default_stone.png",

    access = function(player, data)
        return true
    end,

    formspec = function(player, data, fs)
        fs("label[3,1;This is just a test]")
        return fs
    end,

    fields = function(player, data, fields)

    end,
})
```

I get this by opening my inventory:

![image](https://user-images.githubusercontent.com/61794590/199333413-a3b23989-d3fb-43d8-9192-e26749057c8a.png)

But then I click the "Minify" tab it does nothing.

**Additional context**
- Mod version: git
- Engine version: 5.6-dev
- LuaJIT enabled: Yes
- Operating system: Ubuntu 22.04
- Did you try to disable other mods except i3: no other mods except mine

**Comment by kilbith** [comment]
The `fields` function **must** return `i3.set_fs(player)`

**Comment by AFCMS** [comment]
Oh OK

**Comment by kilbith** [comment]
Or just remove the function `fields` if you don't need it.

**Comment by kilbith** [comment]
Also you need it to add `return fs`

**Comment by kilbith** [comment]
Also you don't need it to add `return fs` in the `formspec` function.
