### ISSUE TITLE
List of recipes not collapsed in progressive mode

### ISSUE THREAD

**Issue by Xardoz** [minetest-mods/i3#81]
**Describe the bug**
The menu doesn't collapse to hide the unknown recipes when progressive mode is set on 'true' in minetest.conf.

**Screenshots**
Here is what I have : ![Not collapsed menu](https://user-images.githubusercontent.com/35117010/199610469-455f4e0c-4b27-4a83-935b-6ffe08a0feac.jpg)

Here is what I saw people have (thanks to this video https://www.youtube.com/watch?v=Xd14BCdEZ3o )
![Collapsed (cf youtube video)](https://user-images.githubusercontent.com/35117010/199611419-37bcb3d9-a000-48d2-b033-789b637dc3bd.jpg)

**Additional context**

- minetest-5.6.1-win64
- i3 [1.12] (tried version on the forum & through the game mod manager)
- Win10
- Tried on Minetest & Mineclone2, same issue.
- It's the only mod activated

**Comment by kilbith** [comment]
Greyed items in Progressive Mode mean that you haven't discovered them yet.
It's the new way of presenting the Progressive Mode.

The video is outdated. Also 1.12 is outdated. Latest is 1.12.2

**Comment by Xardoz** [comment]
Okay ! Thank you for explanation & help ! :)
Sorry for the "false" report !
