### ISSUE TITLE
Progressive mode should be default

### ISSUE THREAD

**Issue by Sazu-bit** [minetest-mods/i3#86]
It's somewhat hard to distribute currently because it forces one of the settings to be set in minetest.conf. I'm trying (wishful thinking) to put some kind of 'survival game' together (nothing overly fancy). 

However, if I want others to join the game, they'll need to make the same edit to their minetest.conf and it's not really convenient. Doing this somewhat breaks what little immersion there is.

I would definitely be interested in any work arounds.

**Comment by kilbith** [comment]
The progressive mode setting is server-side. You don't need your players to enable it in their configuration file.
