### ISSUE TITLE
Quick Crafting not giving replacements back in latest dev version of Minetest

### ISSUE THREAD

**Issue by falsechicken** [minetest-mods/i3#87]
**Describe the bug**
It appears in the latest dev version of Minetest replacements are not working when quick crafting.

**To Reproduce**
Compile latest dev version of Minetest.

Pull latest version of i3

Pull latest version of the farming mod ( tested with https://notabug.org/TenPlus1/farming/commit/28fda57767035e2c46c85098671230f06c5c637c )

Use mortar and pestle to quick craft multiple flour from wheat. Mortar and pestle are consumed when they should be returned as mortar and pestle are defined as a replacement in the flour recipe:

https://notabug.org/TenPlus1/farming/src/master/crops/wheat.lua#L80
```
minetest.register_craft({
	output = "farming:flour",
	recipe = {
		{"farming:wheat", "farming:wheat", "farming:wheat"},
		{"farming:wheat", "farming:mortar_pestle", ""}
	},
	replacements = {{"group:food_mortar_pestle", "farming:mortar_pestle"}}
})
```

**Screenshots**
![screenshot_20230119_084121](https://user-images.githubusercontent.com/401328/213457912-d30ded92-a91b-4745-9ada-7fd5065a35b5.png)
![screenshot_20230119_084132](https://user-images.githubusercontent.com/401328/213457922-879704e7-6743-4795-aa65-63e088a7cab2.png)
![screenshot_20230119_084136](https://user-images.githubusercontent.com/401328/213457930-c525a0b4-4c61-4fa2-9fb3-f9a67d79560b.png)

**Additional context**
I3 Version: https://github.com/minetest-mods/i3/commit/b6b97aa284d65312d12836c1971cb1767ac519df

Minetest Version: https://github.com/minetest/minetest/commit/e21d5613a6288d53edd004d8e020d69792a6d1bf

LuaJit: Enabled

OS: Ubuntu 22.04.1 LTS

**Comment by kilbith** [comment]
https://github.com/minetest-mods/i3/commit/889259ac5eda45e89973e6b2cecd3e7bf3066267

Please test.

**Comment by falsechicken** [comment]
This one is still occurring. Behavior seems the same.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/i3/commit/b6b97aa284d65312d12836c1971cb1767ac519df

Try again.

**Comment by falsechicken** [comment]
Unfortunately not. Still consumes the item.

**Comment by kilbith** [comment]
Make sure that `farming:mortar_pestle` has the group `food_mortar_pestle` in its definition.

Anyway I'm not too bothered to fix this.

**Comment by kilbith** [comment]
Try this commit: https://github.com/minetest-mods/i3/commit/3b1d5691187d60306f1e390f239cce5efc813d00

**Comment by falsechicken** [comment]
That seemed to do it! Thanks!
