### ISSUE TITLE
Quick Crafting multiple items is only using 1 item if said item is non-stackable

### ISSUE THREAD

**Issue by falsechicken** [minetest-mods/i3#88]
**Describe the bug**
It appears in the latest dev version of Minetest quick crafting is only using 1 non-stackable item when crafting multiple items.

**To Reproduce**
Compile latest dev version of Minetest.

Pull latest version of i3

Pull latest version of Techage and it's dependencies ( tested with https://github.com/joe7575/techage/commit/39b7ca719d7dafa606d041fdbe2d3ac00f33267f )

Craft multiple TA2 Quarries. Only one diamond pickaxe is consumed when as shown in the screenshots 4 should have been consumed.

**Screenshots**
![screenshot_20230119_090038](https://user-images.githubusercontent.com/401328/213462708-b63b734f-d4f2-4432-9915-f09d7d6233fe.png)
![screenshot_20230119_090043](https://user-images.githubusercontent.com/401328/213462717-03567f2f-f28a-4f97-8039-fd418d08a087.png)
![screenshot_20230119_090049](https://user-images.githubusercontent.com/401328/213462731-592d0a1a-7575-458e-b252-47b99363124b.png)

**Additional context**
I3 Version: https://github.com/minetest-mods/i3/commit/b95b179a5a558b63f6b144cafd714c0a85212342

Minetest Version: https://github.com/minetest/minetest/commit/e21d5613a6288d53edd004d8e020d69792a6d1bf

LuaJit: Enabled

OS: Ubuntu 22.04.1 LTS

Notes: I would have tested this without Techage but this recipe is what we discovered the bug with and I did not find a recipe in default that had a non-stackable item involved.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/i3/commit/889259ac5eda45e89973e6b2cecd3e7bf3066267

Please test.

**Comment by falsechicken** [comment]
Confirmed. This one seems to be fixed.
