### ISSUE TITLE
Too many exchange to client with HUDCHANGE from server

### ISSUE THREAD

**Issue by MKabe** [minetest-mods/i3#89]
Using the mod with server make a network issue as it send hundreds of HUDCHANGE packets to clients for nothing, it's clearly should be avoided at the moment

This packet is send by player:hud_change(...)
We can found them in hud.lua
It keep continuously send update with empty value when there is nothing to update (each globalstep multiplied by each players connected)
The mod should only send one reset/clear update

To check them you can check packets with Wireshark  and plugin from minetest/util/wireshark/minetest.lua

**Comment by kilbith** [comment]
https://github.com/minetest-mods/i3/commit/ea665fe846358b21a8c9ca0c2581bbf77851f91e should mitigate this.

But there's nothing I can do from the mod to properly "fix" this. Sending hundreds of packets is needed to make e.g. smooth HUD transitions (for the notifications), unfortunately there's no client-side support for this currently in the engine.

Does it cause severe lag when it happens?

**Comment by MKabe** [comment]
I make a pull request #90 , I don't understand the "smooth HUD" nor the engine link, maybe the PR will explain better the problem than my first post :]
